export const tours = [
  {
    id: 1,
    image: "https://koursair-media.s3.us-east-1.amazonaws.com/images/destination/kenya/day1-2.jpg",
    category: "Adventure",
    title: "Kenya Business Excursion: Where the World Meets the Wild",
    country: "kenya",
    slug: "kenya-business-excursion-where-the-world-meets-the-wild",
    link: "/tour/kenya",
    duration: "9 days",
    dates: "Sep 7 – Sep 15, 2026",
    price: 6850,
    rating: 5,
    // reviews: 343,
    isLiked: true,
  },
  {
    id: 2,
    image: "https://koursair-media.s3.us-east-1.amazonaws.com/images/destination/dubai/museum_of_the_future_dubai.jpg",
    category: "HISTORIC",
    slug: "dubai-discovery",
    country: "dubai",
    title: "Dubai Discovery",
    duration: "6 days",
       dates: "Coming Soon",
    price: 2749,
    rating: 4.8,
    isLiked: true,
  },
  {
    id: 3,
    image: "https://koursair-media.s3.us-east-1.amazonaws.com/images/destination/tihati/tihati.jpg",
    category: "Tropical Escape",
    country: "tahiti",
    title: "Tahiti Meets Endless Summer",
    slug: "tahiti-endless-summer-experience",
    duration: "6 days",
       dates: "Mar 28 - Apr 3, 2026",
    price: 3250,
    rating: 4.8,
    isLiked: true,
  },
  {
    id: 4,
    image: "https://koursair-media.s3.us-east-1.amazonaws.com/images/destination/india/yoga-healing/main-1.jpg",
    category: "WALKING",
    slug: "rishikesh-haridwar-yoga-healing",
    country: "india",
    title: "Rishikesh & Haridwar Yoga Healing",
    link: "/destinations",
    description:
      "Experience spiritual serenity with our thoughtfully curated Rishikesh and Haridwar yoga and healing journey.",
    duration: "7 days",
    price: 4779,
    rating: 8.0,
    isLiked: false,
  },
  {
    id: 5,
    image: "https://koursair-media.s3.us-east-1.amazonaws.com/images/destination/dubai/BurjKhalifa.jpg",
    category: "LUXURY",
    slug: "dubai-luxury-adventure",
    country: "dubai",
    title: "Dubai Luxury Adventure",
    link: "/destinations",
    description:
      "Unveil the splendor of Dubai, where every moment redefines luxury and sophistication.",
    duration: "6 days",
    price: 6389,
    rating: 7.0,
    reviews: 350,
    isLiked: true,
  },

  {
    id: 6,
    image: "https://koursair-media.s3.us-east-1.amazonaws.com/images/destination/misc/japan.jpg",
    category: "HISTORIC",
    title: "Japan Getaway",
    country: "japan",
    slug: "japan-romantic-getaway",
    link: "/destinations",
    description:
      "Indulge in the perfect blend of relaxation, romance, and adventure with Japan",
    duration: "3 days",
    price: 2550,
    rating: 7.0,
    reviews: 350,
    isLiked: false,
  },
  {
    id: 7,
    image: "https://koursair-media.s3.us-east-1.amazonaws.com/images/destination/thailand/Thailand_Street.jpg",
    category: "MUSEUM",
    country: "thailand",
    title: "Thailand Vibrant Escape",
    slug: "thailand-vibrant-escape",
    link: "/destinations",
    description:
      "Discover the best of Thailand with a perfect mix of Island Hopping & City Exploration.",
    duration: "10 days",
    price: 4799,
    rating: 8.0,
    reviews: 850,
    isLiked: true,
  },
];